no display found. Using non-interactive Agg backend
[5, 5, 5]
Cifar10: True; cifar100: False
False
Files already downloaded and verified
count0: 487386

Epoch: [1 | 180] LR: 0.100000
Epoch: [1][0/391]	Time 0.533 (0.533)	Data 0.162 (0.162)	Loss 2.9555 (2.9555)	Acc@1 20.312 (20.312)	Acc@5 54.688 (54.688)
Epoch: [1][64/391]	Time 0.533 (0.488)	Data 0.002 (0.004)	Loss 2.5202 (2.6816)	Acc@1 27.344 (22.404)	Acc@5 86.719 (76.538)
Epoch: [1][128/391]	Time 0.505 (0.500)	Data 0.002 (0.003)	Loss 2.2630 (2.5329)	Acc@1 40.625 (27.162)	Acc@5 92.188 (81.086)
Epoch: [1][192/391]	Time 0.545 (0.505)	Data 0.002 (0.003)	Loss 2.2973 (2.4474)	Acc@1 28.906 (29.663)	Acc@5 82.812 (83.480)
Epoch: [1][256/391]	Time 0.521 (0.509)	Data 0.002 (0.002)	Loss 2.0128 (2.3718)	Acc@1 40.625 (32.512)	Acc@5 92.188 (85.068)
Epoch: [1][320/391]	Time 0.523 (0.510)	Data 0.002 (0.002)	Loss 2.1560 (2.2983)	Acc@1 42.969 (35.020)	Acc@5 91.406 (86.444)
Epoch: [1][384/391]	Time 0.529 (0.512)	Data 0.002 (0.002)	Loss 1.7285 (2.2314)	Acc@1 55.469 (37.376)	Acc@5 92.969 (87.502)
Traceback (most recent call last):
  File "main.py", line 725, in <module>
    main()
  File "main.py", line 323, in main
    use_gpu)
  File "main.py", line 545, in test
    outputs = model(inputs)
  File "/home/jessica.buehler/env/local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jessica.buehler/MA_Source/src/n2n.py", line 471, in forward
    _x = self.module_list[j](_x)
  File "/home/jessica.buehler/env/local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jessica.buehler/env/local/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 345, in forward
    return self.conv2d_forward(input, self.weight)
  File "/home/jessica.buehler/env/local/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 342, in conv2d_forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 10.76 GiB total capacity; 398.86 MiB already allocated; 13.94 MiB free; 426.00 MiB reserved in total by PyTorch)
no display found. Using non-interactive Agg backend
[5, 5, 5]
Cifar10: True; cifar100: False
False
Files already downloaded and verified
count0: 487386

Epoch: [1 | 180] LR: 0.100000
Epoch: [1][0/391]	Time 0.584 (0.584)	Data 0.173 (0.173)	Loss 3.3366 (3.3366)	Acc@1 9.375 (9.375)	Acc@5 43.750 (43.750)
Epoch: [1][64/391]	Time 0.458 (0.503)	Data 0.001 (0.004)	Loss 2.6299 (2.8372)	Acc@1 28.906 (20.529)	Acc@5 78.906 (71.803)
Epoch: [1][128/391]	Time 0.529 (0.510)	Data 0.002 (0.003)	Loss 2.3981 (2.6762)	Acc@1 32.031 (24.800)	Acc@5 87.500 (77.665)
Epoch: [1][192/391]	Time 0.525 (0.511)	Data 0.002 (0.003)	Loss 2.3546 (2.5580)	Acc@1 32.031 (28.068)	Acc@5 89.062 (81.226)
Epoch: [1][256/391]	Time 0.520 (0.514)	Data 0.001 (0.003)	Loss 2.1062 (2.4695)	Acc@1 43.750 (30.885)	Acc@5 85.938 (83.439)
Epoch: [1][320/391]	Time 0.523 (0.516)	Data 0.002 (0.002)	Loss 2.0051 (2.3824)	Acc@1 52.344 (33.745)	Acc@5 89.062 (85.195)
Epoch: [1][384/391]	Time 0.505 (0.517)	Data 0.002 (0.002)	Loss 1.7309 (2.3123)	Acc@1 57.812 (36.181)	Acc@5 96.094 (86.429)
Traceback (most recent call last):
  File "main.py", line 725, in <module>
    main()
  File "main.py", line 323, in main
    use_gpu)
  File "main.py", line 545, in test
    outputs = model(inputs)
  File "/home/jessica.buehler/env/local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jessica.buehler/MA_Source/src/n2n.py", line 471, in forward
    _x = self.module_list[j](_x)
  File "/home/jessica.buehler/env/local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jessica.buehler/env/local/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 345, in forward
    return self.conv2d_forward(input, self.weight)
  File "/home/jessica.buehler/env/local/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 342, in conv2d_forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 10.76 GiB total capacity; 398.86 MiB already allocated; 13.94 MiB free; 426.00 MiB reserved in total by PyTorch)
no display found. Using non-interactive Agg backend
[5, 5, 5]
Cifar10: True; cifar100: False
False
Files already downloaded and verified
count0: 487386

Epoch: [1 | 180] LR: 0.100000
Epoch: [1][0/391]	Time 0.505 (0.505)	Data 0.207 (0.207)	Loss 3.4904 (3.4904)	Acc@1 7.031 (7.031)	Acc@5 50.000 (50.000)
Epoch: [1][64/391]	Time 0.509 (0.503)	Data 0.002 (0.005)	Loss 2.7408 (2.8987)	Acc@1 23.438 (17.812)	Acc@5 77.344 (68.209)
Epoch: [1][128/391]	Time 0.542 (0.514)	Data 0.001 (0.003)	Loss 2.4489 (2.7125)	Acc@1 23.438 (22.123)	Acc@5 90.625 (75.957)
Epoch: [1][192/391]	Time 0.511 (0.518)	Data 0.001 (0.003)	Loss 2.2568 (2.6050)	Acc@1 40.625 (25.109)	Acc@5 90.625 (79.696)
Epoch: [1][256/391]	Time 0.552 (0.521)	Data 0.002 (0.003)	Loss 2.3234 (2.5189)	Acc@1 35.156 (27.718)	Acc@5 87.500 (82.062)
Epoch: [1][320/391]	Time 0.441 (0.522)	Data 0.002 (0.003)	Loss 2.2334 (2.4457)	Acc@1 31.250 (30.121)	Acc@5 92.188 (83.708)
Epoch: [1][384/391]	Time 0.554 (0.524)	Data 0.002 (0.002)	Loss 2.1955 (2.3849)	Acc@1 36.719 (32.208)	Acc@5 89.062 (84.892)
Traceback (most recent call last):
  File "main.py", line 725, in <module>
    main()
  File "main.py", line 323, in main
    use_gpu)
  File "main.py", line 545, in test
    outputs = model(inputs)
  File "/home/jessica.buehler/env/local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jessica.buehler/MA_Source/src/n2n.py", line 471, in forward
    _x = self.module_list[j](_x)
  File "/home/jessica.buehler/env/local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jessica.buehler/env/local/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 345, in forward
    return self.conv2d_forward(input, self.weight)
  File "/home/jessica.buehler/env/local/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 342, in conv2d_forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 10.76 GiB total capacity; 398.86 MiB already allocated; 13.94 MiB free; 426.00 MiB reserved in total by PyTorch)
no display found. Using non-interactive Agg backend
[5, 5, 5]
Cifar10: True; cifar100: False
False
Files already downloaded and verified
count0: 487386

Epoch: [1 | 180] LR: 0.100000
Traceback (most recent call last):
  File "main.py", line 725, in <module>
    main()
  File "main.py", line 318, in main
    use_gpu_num)
  File "main.py", line 442, in train
    outputs = model.forward(inputs)
  File "/home/jessica.buehler/MA_Source/src/n2n.py", line 489, in forward
    x = self.module_list[j](x)
  File "/home/jessica.buehler/env/local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jessica.buehler/env/local/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 345, in forward
    return self.conv2d_forward(input, self.weight)
  File "/home/jessica.buehler/env/local/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 342, in conv2d_forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 10.76 GiB total capacity; 163.44 MiB already allocated; 19.94 MiB free; 202.00 MiB reserved in total by PyTorch)
























 ab hier mit pruneTrain
